baseURL: "https://ajulusthoughts2-1.netlify.app"
languageCode: "en-us"
title: "Ajulu's Thoughts"
pygmentsstyle: 'monokai'
enableEmoji: true
paginate: 14
metaDataFormat: yaml
enableGitInfo: true
enableRobotsTXT: true

social:
  facebook: "stephenajulu"
  twitter: "stephenajulu"
  github: "stephenajulu/"
  instagram: "stephenajulu"
  linkedin: "stephenajulu"
  dribbble: "stephenajulu"
  youtube: "UC043ZXL-t3yqtgcIxJmkHuA"
  
params:
  description: "Tech, Lifestyle, Cybersecurity, Finance, Design, Dev Among Other Thoughts with Ajulu."
  images: "images/about.png"
  hero: "images/about.png"
  default_image: "images/about.png"
  GithubEdit: "https://github.com/stephenajulu/ajulusthoughts2/edit/master/content/"
  formaction: "https://app.convertkit.com/forms/2023413/subscriptions"
  twitter: "@stephenajulu"
  author: "Stephen Ajulu"
  creator: "Stephen Ajulu"
  toc: true
  adsense:
    client: "ca-pub-2099668045881016"
    inArticleSlot: "5485551778"
    BannerSlot: "8662937936"
  
taxonomies:
  author: authors
  tag: tags
  category: categories
  
markup:
  goldmark:
    renderer:
      unsafe: true
    tableOfContents:
      endLevel: 4
      ordered: true
      startLevel: 2
      
related:
  threshold: 0
  includeNewer: true
  toLower: false
  indices:
  - name: categories
    weight: 200
  - name: tags
    weight: 500
  - name: keywords
    weight: 200
  - name: date
    weight: 10
  - name: title
    weight: 50

menu:
  main:
  - identifier: about
    name: About
    url: about
    weight: 0
    
outputs:
  home: 
  - HTML
  - RSS
  - JSON
